const workers = [
  {
    id: 1,
    name: "Ramesh Vishwakarma",
    initials: "RV",
    trade: "Plumber",
    city: "Mumbai",
    area: "Andheri West",
    rating: 4.9,
    jobs: 187,
    exp: "12 yrs",
    phone: "9876543210",
    desc: "Pipe leakage, bathroom fitting, motor repair. Emergency service available 24/7.",
  },
  {
    id: 2,
    name: "Savitri Devi",
    initials: "SD",
    trade: "Tailor",
    city: "Delhi",
    area: "Lajpat Nagar",
    rating: 4.8,
    jobs: 303,
    exp: "15 yrs",
    phone: "9123456789",
    desc: "Saree blouse, salwar suit, school uniforms. Home visits available on request.",
  },
  {
    id: 3,
    name: "Mukesh Patel",
    initials: "MP",
    trade: "Electrician",
    city: "Bengaluru",
    area: "Koramangala",
    rating: 4.7,
    jobs: 234,
    exp: "8 yrs",
    phone: "9988776655",
    desc: "Wiring, MCB, inverter installation, fan fitting. Licensed electrician.",
  },
  {
    id: 4,
    name: "Shyam Lal",
    initials: "SL",
    trade: "Carpenter",
    city: "Pune",
    area: "Kothrud",
    rating: 4.6,
    jobs: 156,
    exp: "20 yrs",
    phone: "9871234560",
    desc: "Furniture making and repair. Windows, doors, wardrobes — all woodwork.",
  },
  {
    id: 5,
    name: "Anita Rajput",
    initials: "AR",
    trade: "Cook",
    city: "Hyderabad",
    area: "Banjara Hills",
    rating: 5.0,
    jobs: 412,
    exp: "10 yrs",
    phone: "9765432109",
    desc: "Home cooking, party catering, tiffin service. North & South Indian cuisine.",
  },
  {
    id: 6,
    name: "Dinesh Sharma",
    initials: "DS",
    trade: "Painter",
    city: "Jaipur",
    area: "Malviya Nagar",
    rating: 4.5,
    jobs: 98,
    exp: "6 yrs",
    phone: "9654321098",
    desc: "Interior, exterior, texture painting. Materials included in service.",
  },
  {
    id: 7,
    name: "Kavita Nair",
    initials: "KN",
    trade: "Tailor",
    city: "Kochi",
    area: "Ernakulam",
    rating: 4.9,
    jobs: 278,
    exp: "18 yrs",
    phone: "9745123456",
    desc: "Specialises in Kerala saree blouses, kurtas, and western alterations.",
  },
  {
    id: 8,
    name: "Suresh Yadav",
    initials: "SY",
    trade: "Plumber",
    city: "Lucknow",
    area: "Gomti Nagar",
    rating: 4.6,
    jobs: 121,
    exp: "9 yrs",
    phone: "9812345670",
    desc: "All plumbing work including geyser installation, pipe fitting, and tank repair.",
  },
  {
    id: 9,
    name: "Priya Sen",
    initials: "PS",
    trade: "Cook",
    city: "Kolkata",
    area: "Salt Lake",
    rating: 4.8,
    jobs: 198,
    exp: "7 yrs",
    phone: "9933445566",
    desc: "Bengali cuisine specialist. Tiffin service, party catering, and home cooking.",
  },
];

const chartData = [
  { label: "Plumber",     value: 134 },
  { label: "Electrician", value: 98  },
  { label: "Tailor",      value: 87  },
  { label: "Carpenter",   value: 56  },
  { label: "Cook",        value: 72  },
  { label: "Painter",     value: 53  },
];
